version: '3.8'
services:
  hmi1:
    build:
      context: ./src/EquipmentStates.HMI
    ports:
      - "5001:5001"   # HMI1 (HTTP)
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - EQUIPMENT_ID=11111111-1111-1111-1111-111111111111
      - PUBLIC_BASE_URL=http://localhost:5001
      - OPCUA_ENDPOINT=opc.tcp://opcua:4840/freeopcua/server/
  hmi2:
    build:
      context: ./src/EquipmentStates.HMI
    ports:
      - "5002:5002"   # HMI2 (HTTP)
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - EQUIPMENT_ID=22222222-2222-2222-2222-222222222222
      - PUBLIC_BASE_URL=http://localhost:5002
      - OPCUA_ENDPOINT=opc.tcp://opcua:4840/freeopcua/server/

  ordersapi:
    build:
      context: ./src/EquipmentStates.OrdersAPI
    ports:
      - "5003:5003"   # HTTP
    environment:
      - ASPNETCORE_URLS=http://+:5003

  opcua:
    build:
      context: ./src/opcua_python_server
    ports:
      - "4840:4840"
